# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eWM5cxawBAcj2Yf319me_T1RSG-aK-Fj
"""

import pandas as pd
import numpy as np
import folium
import random
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score
import ipywidgets as widgets
from IPython.display import display, HTML, clear_output
from geopy.geocoders import Nominatim # Import Nominatim geocoder
import time # Import time for delays to avoid rate limiting

# -----------------------
# VERİ
# ------------------------
# Define a dictionary for city information including neighborhoods and coordinate ranges
city_info = {
    "İstanbul": {
        "districts": [
            "Avcılar","Küçükçekmece","Bakırköy","Zeytinburnu",
            "Fatih","Beşiktaş","Üsküdar","Kadıköy",
            "Pendik","Ümraniye","Esenyurt","Silivri"
        ],
        "lat_center": 41.0082, # Approximate center for Istanbul
        "lon_center": 28.9784
    },

    "Bursa": {
        "districts": [
            "Osmangazi","Yıldırım","Nilüfer","Gemlik",
            "Mudanya","İnegöl","Kestel","Gürsu",
            "Karacabey","Mustafakemalpaşa"
        ],
        "lat_center": 40.1885, # Approximate center for Bursa
        "lon_center": 29.0609
    },

    "Kocaeli": {
        "districts": [
            "İzmit","Gebze","Gölcük",
            "Körfez","Derince","Başiskele"
        ],
        "lat_center": 40.7656, # Approximate center for Kocaeli
        "lon_center": 29.9405
    },

    "Yalova": {
        "districts": [
            "Merkez","Çiftlikköy","Altınova","Çınarcık"
        ],
        "lat_center": 40.6558, # Approximate center for Yalova
        "lon_center": 29.2667
    },

    "Sakarya": {
        "districts": [
            "Adapazarı","Serdivan","Erenler",
            "Akyazı","Hendek"
        ],
        "lat_center": 40.7755, # Approximate center for Sakarya
        "lon_center": 30.4020
    }
}

all_cities_data = []

np.random.seed(42) # Set a seed for reproducibility of data generation
geolocator = Nominatim(user_agent="colab_earthquake_analysis") # Initialize geolocator

for city, info in city_info.items():
    num_neighborhoods = len(info["districts"])

    latitudes = []
    longitudes = []
    precise_coords = info.get("precise_coords", {})

    # Use city-specific center for fallback if geocoding fails
    city_lat_center = info.get("lat_center", 39.0) # Default to a general Turkey center if not specified
    city_lon_center = info.get("lon_center", 35.0) # Default to a general Turkey center if not specified

    # The original code had 'neighborhoods' which is not in city_info. Use 'districts' instead.
    for neighborhood in info["districts"]:
        if neighborhood in precise_coords:
            lat, lon = precise_coords[neighborhood]
            latitudes.append(lat)
            longitudes.append(lon)
        else:
            # Attempt to geocode the neighborhood for more accurate placement
            try:
                location = geolocator.geocode(f"{neighborhood}, {city}, Turkey", timeout=5)
                if location:
                    latitudes.append(location.latitude)
                    longitudes.append(location.longitude)
                else:
                    print(f"Geocoding failed for {neighborhood}, {city}. Using localized random coordinates.")
                    # Fallback to random generation within a small range around the city's center
                    latitudes.append(np.random.uniform(city_lat_center - 0.05, city_lat_center + 0.05))
                    longitudes.append(np.random.uniform(city_lon_center - 0.05, city_lon_center + 0.05))
            except Exception as e:
                print(f"Geocoding failed for {neighborhood}, {city}: {e}. Falling back to localized random coordinates.")
                # Fallback to random generation within a small range around the city's center
                latitudes.append(np.random.uniform(city_lat_center - 0.05, city_lat_center + 0.05))
                longitudes.append(np.random.uniform(city_lon_center - 0.05, city_lon_center + 0.05))
            time.sleep(1) # Add a small delay to respect Nominatim usage policy


    city_data = {
        "Sehir": [city] * num_neighborhoods,
        "Mahalle": info["districts"],

        # Gerçekçi değer aralıkları
        "Hasar": np.random.randint(55, 90, num_neighborhoods),
        "Nufus": np.random.randint(50000, 800000, num_neighborhoods),
        "65_plus": np.random.randint(8, 22, num_neighborhoods),
        "Hastane_Uzaklik": np.round(np.random.uniform(0.5, 8, num_neighborhoods), 1),
        "Yol_Erisim": np.random.randint(0, 2, num_neighborhoods),
        "Bina_Yasi_Ortalama": np.random.randint(8, 45, num_neighborhoods),
        "Zemin_Tipi": np.random.choice(
            ["Saglam", "Orta", "Zayif"],
            num_neighborhoods,
            p=[0.35, 0.40, 0.25]
        ),

        "Latitude": latitudes,
        "Longitude": longitudes
    }
    all_cities_data.append(pd.DataFrame(city_data))

df = pd.concat(all_cities_data, ignore_index=True)

# -----------------------
# ŞEHİR SEÇİMİ VE SİSTEM BAŞLATMA WIDGETLARI
# -----------------------
# This initial dropdown will not be used for the first run, but kept for context
initial_city_dropdown = widgets.Dropdown(
    options=df['Sehir'].unique(),
    description='Ana Şehir Seçimi:'
)

initial_start_button = widgets.Button(description="SİSTEMİ BAŞLAT", button_style='danger')

# Create an Output widget to hold dynamic content, allowing for clearing and updating
output_area = widgets.Output()
# Removed: New output areas for surrounding city controls and their analysis
# surrounding_controls_output = widgets.Output()
# surrounding_analysis_output = widgets.Output()

# -----------------------
# ANA ANALİZ FONKSİYONU
# -----------------------
def run_analysis_for_city(city_name, magnitude):
    df_sehir = df[df['Sehir'] == city_name].copy()

    # Use mean coordinates of the selected city as the earthquake epicenter for that city's analysis
    merkez_lat = df_sehir['Latitude'].mean()
    merkez_lon = df_sehir['Longitude'].mean()

    # Validate merkez_lat and merkez_lon to prevent errors with Folium map initialization
    if pd.isna(merkez_lat) or pd.isna(merkez_lon):
        print(f"Hata: {city_name} için merkez koordinatları geçersiz. Harita oluşturulamıyor.")
        return

    # Calculate distance from the city's (simulated) epicenter
    df_sehir['Merkez_Uzaklik'] = np.sqrt(
        (df_sehir['Latitude'] - merkez_lat)**2 +
        (df_sehir['Longitude'] - merkez_lon)**2
    )

    # Map Zemin_Tipi to numerical values for the model
    zemin_mapping = {'Saglam': 1, 'Orta': 2, 'Zayif': 3}
    df_sehir['Zemin_Tipi_Kod'] = df_sehir['Zemin_Tipi'].map(zemin_mapping)

    # Yapay zekâ veri (Gerçek skorun daha karmaşık hesaplanması)
    # The 'Gercek' score is a proxy for vulnerability/impact based on various factors
    df_sehir['Gercek'] = (
        df_sehir['Hasar'] * 0.3 +
        df_sehir['65_plus'] * 0.15 +
        df_sehir['Nufus'] * 0.0003 +
        df_sehir['Hastane_Uzaklik'] * 3 +
        df_sehir['Merkez_Uzaklik'] * 70 +
        df_sehir['Bina_Yasi_Ortalama'] * 0.5 +
        df_sehir['Zemin_Tipi_Kod'] * 10
    )

    # Features for the Random Forest Regressor
    X = df_sehir[['Hasar','Nufus','65_plus','Hastane_Uzaklik','Yol_Erisim','Merkez_Uzaklik', 'Bina_Yasi_Ortalama', 'Zemin_Tipi_Kod']]
    y = df_sehir['Gercek']

    # Train-test split for model evaluation
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Initialize and train the Random Forest Regressor model
    model = RandomForestRegressor(random_state=42) # Added random_state for reproducibility
    model.fit(X_train, y_train)

    # Predict on test set and evaluate model performance
    y_pred = model.predict(X_test)
    mae = mean_absolute_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    # Predict on the full dataset to get scores for all neighborhoods for mapping
    df_sehir['Skor'] = model.predict(X)

    # Assign 'Oncelik' based on quantiles
    df_sehir["Oncelik"] = "Orta" # Default to Orta
    df_sehir.loc[df_sehir["Skor"] >= df_sehir["Skor"].quantile(0.50), "Oncelik"] = "Yüksek"
    df_sehir.loc[df_sehir["Skor"] >= df_sehir["Skor"].quantile(0.80), "Oncelik"] = "Kritik"

    df_sehir = df_sehir.sort_values(by='Skor', ascending=False)

    # -----------------------
    # BAŞLIK VE SONUÇ EKRANI
    # -----------------------
    display(HTML(f"""
    <h1 style='color:red'>🚨 DEPREM ACİL DURUM SİSTEMİ 🚨</h1>
    <h3>{city_name} şehrinde <b>{magnitude}</b> büyüklüğünde deprem meydana geldi.</h3>
    <h2 style='color:red'>ÖNCELİK: {df_sehir.iloc[0]['Mahalle']}</h2>
    <p>Model Değerlendirme:</p>
    <ul>
        <li>Ortalama Mutlak Hata (MAE): {mae:.2f}</li>
        <li>R-kare (R2) Skoru: {r2:.2f}</li>
    </ul>
    """))

    display(df_sehir[['Mahalle','Oncelik','Hasar','Nufus','65_plus','Hastane_Uzaklik','Bina_Yasi_Ortalama','Zemin_Tipi','Skor']])
    print(f"\nMerkez Koordinatları: Latitude={merkez_lat:.4f}, Longitude={merkez_lon:.4f}")
    print(f"İlk 5 Mahalle Koordinatları:\n{df_sehir[['Mahalle', 'Latitude', 'Longitude']].head()}")

    # -----------------------
    # HARİTA GÖRSELLEŞTİRMESİ
    # -----------------------
    m = folium.Map(location=[merkez_lat, merkez_lon], zoom_start=12, tiles='OpenStreetMap') # Increased zoom and added tiles

    # Earthquake wave circles (only for Istanbul)
    if city_name == "İstanbul":
        for r in range(2000,8000,800):
            folium.Circle(
                location=[merkez_lat, merkez_lon],
                radius=r,
                color='red',
                fill=True,
                fill_opacity=0.05
            ).add_to(m)

    # Neighborhood markers colored by score priority
    for i,row in df_sehir.iterrows():
        if row['Oncelik'] == 'Kritik':
            color='red'
            size=18
        elif row['Oncelik'] == 'Yüksek':
            color='orange'
            size=15
        else: # 'Orta'
            color='yellow'
            size=12

        folium.CircleMarker(
            location=[row['Latitude'], row['Longitude']],
            radius=size,
            color=color,
            fill=True,
            fill_color=color,
            fill_opacity=0.9,
            popup=f"{row['Mahalle']} - Skor: {row['Skor']:.1f}"
        ).add_to(m)

    display(m)

# -----------------------
# BAŞLANGIÇ SİSTEMİNİ ÇALIŞTIRAN HANDLER
# -----------------------
def sistem_baslat_handler(b):
    with output_area: # This output_area is for Istanbul's analysis
        clear_output(wait=True) # Clear previous content in the output area

        # Use the city selected in the dropdown
        selected_city = initial_city_dropdown.value

        deprem_buyuklukleri = {
            "İstanbul": 7.5,
            "Bursa": 6.8,
            "Kocaeli": 7.0,
            "Yalova": 6.6,
            "Sakarya": 6.5
        }

        magnitude = deprem_buyuklukleri[selected_city] # Use magnitude for the selected city
        run_analysis_for_city(selected_city, magnitude)

        # Removed the automatic analysis of surrounding cities
        # if selected_city == "İstanbul":
        #     cevre_sehirler = [
        #         ("Bursa", 6.8),
        #         ("Kocaeli", 7.0),
        #         ("Yalova", 6.6),
        #         ("Sakarya", 6.5)
        #     ]

        #     for sehir, mag in cevre_sehirler:
        #         print("\n" + "="*60)
        #         run_analysis_for_city(sehir, mag)

# Attach the handler to the initial start button
initial_start_button.on_click(sistem_baslat_handler)

# Display initial widgets and the main output area container
display(
    HTML("""
    <h1 style='color:red;text-align:center'>
    🚨 AKDS - Afet Karar Destek Sistemi 🚨
    </h1>

    <h2 style='text-align:center'>
    İstanbul'da 7.5 büyüklüğünde deprem meydana geldi.
    </h2>

    <h3 style='text-align:center'>
    Yardım gönderilecek şehri seçiniz.
    </h3>
    """),
    initial_city_dropdown,
    initial_start_button,
    output_area
)